# Generated by Django 5.1.6 on 2025-02-24 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_payment_course_remove_payment_lesson_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="payment",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="payment",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="email",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="password",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="username",
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
