# Generated by Django 5.1.6 on 2025-03-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_link_payment_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="data_payment",
            field=models.DateField(auto_now=True, verbose_name="Дата оплаты"),
        ),
    ]
