# Generated by Django 5.1.6 on 2025-02-20 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название курса", max_length=150, verbose_name="Название курса"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="materials/course", verbose_name="Предварительный просмотр"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Краткое описание курса", null=True, verbose_name="Описание курса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название урока", max_length=150, verbose_name="Название урока"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="materials/lesson", verbose_name="Предварительный просмотр"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Краткое описание урока", null=True, verbose_name="Описание урока"
                    ),
                ),
                ("url_video", models.URLField(verbose_name="Ссылка на видео")),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
