# Generated by Django 5.1.6 on 2025-02-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="url_video",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка на видео"),
        ),
    ]
