# Generated by Django 5.1.6 on 2025-03-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="status_subscrip",
        ),
    ]
